### ISSUE TITLE
Legacy Open Source?

### ISSUE THREAD

**Issue by augustresende** [HackerExperience/Heview#1]
When?

**Comment by augustresende** [comment]
@renatomassaro

**Comment by advocaite** [comment]
yeah sucks you promised it then give it to some people who are making money from it
do us all a favour and release it like you said i your blog we should not have to buy primum from another site when we supported you on the original one.. please release the source code

**Comment by augustresende** [comment]
up

**Comment by augustresende** [comment]
@renatomassaro

**Comment by augustresende** [comment]
@renatomassaro

**Comment by augustresende** [comment]
@renatomassaro

**Comment by augustresende** [comment]
@renatomassaro

**Comment by advocaite** [comment]
@renatomassaro  say something im giving up on you

**Comment by advocaite** [comment]
thankyou
